### ISSUE TITLE
1.19.4 Backport

### ISSUE THREAD

**Issue by Scarlaid** [devpelux/sodium-blendingregistry#2]
### Description

Will there a 1.19 backport? This mod really helps with taking good screenshot in Minecraft

Some mods are still on 1.19.4, which is why might not only me still sticking with 1.19.4 as the main game

**Comment by Scarlaid** [comment]
Nevermind, this mod can run fine on 1.19

**Comment by devpelux** [comment]
1.20 uses the 1.20 releases of sodium and could have potential incompatibilities.

**Comment by devpelux** [comment]
Fixed in https://github.com/devpelux/sodium-blendingregistry/commit/1f443893838adab8bda9d1848bc9c4cc55d9267d
