### ISSUE TITLE
1.20.1 version does not work

### ISSUE THREAD

**Issue by Tapacywka** [devpelux/sodium-blendingregistry#3]
### Description

How it was tested: 2 screenshots were taken in a place where the biome changes from plains to savannah (before installing the mod and after). Both screenshots look identical, no change in transitions like those shown in the example on the mod page.

### Affected releases

0.4.10.1

### Minecraft

1.20.1

**Comment by Tapacywka** [comment]
Without mod: https://imgur.com/a/eHzjPxP
With mod: https://imgur.com/a/XSsV216

**Comment by devpelux** [comment]
This plugin does not changes sodium behavior or improves it, but only fixes a bug of this behavior causing color issues and even random crashes with some mods (like my mod Terravibe).

![img1](https://github.com/devpelux/sodium-blendingregistry/raw/d17a1e1ce1b994f4e662ad4223911563fe2a064e/assets/img1.png)

![img2](https://github.com/devpelux/sodium-blendingregistry/raw/d17a1e1ce1b994f4e662ad4223911563fe2a064e/assets/img2.png)

The savannah biome works as expected.
I updated the readme, by removing the grass image, which led to misunderstandings.

You should use this mod only if you have problems like the two images above.
