### ISSUE TITLE
[INCOMPATIBLE] Sodium v0.5 Released - SBR is incompatible

### ISSUE THREAD

**Issue by LokeYourC3PH** [devpelux/sodium-blendingregistry#4]
### Description

Sodium released a huge update today, and SBR is as such incompatible with the latest Sodium version. Please look into this if possible, and if Sodium fixed this themselves, mark the mod as either outdated & won't be updated, or deprecated.

Thank you :)

### Affected releases

0.4.10.1

### Minecraft

1.20.1

EDIT: And according to Sodium https://github.com/CaffeineMC/sodium-fabric/issues/895 , the issue was fixed and I think that this mod is therefore not needed anymore.

**Comment by Tapacywka** [comment]
![image](https://github.com/devpelux/sodium-blendingregistry/assets/71761232/f55809b5-9a91-4982-be62-e33e29d9e2d1)

**Comment by devpelux** [comment]
Sodium 0.5 includes the fix in his codebase, so this plugin is not needed anymore.
This repos will become archived.
